travis:
  secure:
    BINSTAR_TOKEN: sCX9cbqkoOJs6BlwGvqr04GBHKN5yKIgmKc8bSGp+M6KMCVNgYJ08lVbgoHYAHcJEdb81Sxaj3RGATHVwEmPv6ayEQCNZ8aR9SYkSGcZKyDjQqN7ShM1qXUiC+Dsbwi7vWEG+Gd3SehyGGmiaXUbVplhiWUDw2es+QC/cCn132O2vSSzNuNfHHQOt0J0VJkBct6sX/Dgesujw5aK6ASpka22PrLVISq0lA7e7IxIkE5qQq3PK8dCv2Uj46xiaLr4YZxSVTZvloQ4uJDQVexG0WL4Sn1WVi3s7hGRYc2tvPwPYlQKRHV8S6fvYUp16WqPjZvwXAVg0qCnswplWwWCmcNnVz6EirnzC/qM676DvcUNSPPhbQztZG+USXtzKzMIRtJyGx+6aAbWhzRa07+pkBWYwsR+45axOGf8rlzljfbmxcW/9eXeUaa2UuRvTNr0QtHLfH4rRCnIqDQ5nymaDgcpzDRUWv2J0/9I/nQbTKoWVOz+16rFCCRYtmcHJTQ2ZlnRclb3Jr3CHLPWKaghz4WyGEQC8IU5UJW26KaAqsIUilyHyP67YrX5aj4zU/NwpgJoFF/tzQnSR6oMj8gviiOlRx14dBa0LsL8sNPCIGfedIu+9RwDbCL1ky3TT1MNA1AS6UbjcPtiVJZn8wx7QDb6RVdrQkt5ONZhufMv3w4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
